# Copyright 2021 Teak.io, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

orbs:
  teak: teak/sdk-utils@0.9

parameters:
  region:
    type: string
    default: us-east-1
  in_build_account_slug:
    type: string
    default: "stage-ci-cd"
  in_deploy_account_slug:
    type: string
    default: "stage-workload"

references:
  packer-build: &packer-build
    version: 1.7.5-dev2
    github_releases_user: AlexSc
    gpg_key_id: EC3A3F7C6C4F9D25
    name: "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"
    image: "cimg/base:current-20.04"
    pre-steps:
      - run:
          name: "Prepare Circle image"
          command: |
            sudo apt-get update && sudo apt-get install -y --no-install-recommends ansible

            ip=$(curl -s https://api.ipify.org)
            echo "My public IP address is: $ip"
    post-steps:
      - store_artifacts:
          path: "manifests/"
    var: "region=<< pipeline.parameters.region >>,build_account_canonical_slug=<< pipeline.parameters.in_build_account_slug >>,cost_center=base_image,datadog_api_key=$DATADOG_API_KEY"
    context:
      - AWS-Write
      - DataDog
  # node12-build: &node12-build
  #   <<: *packer-build
  #   name: "Generate Node 12 Image (<< pipeline.parameters.in_build_account_slug >>)"
  #   post-steps:
  #     - store_artifacts:
  #         path: "language_images/node12/manifests"
  #   packer_working_directory: "language_images/node12"
  #   requires:
  #     - "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"
  # ruby30-build: &ruby30-build
  #   <<: *packer-build
  #   name: "Generate Ruby 3.0 Image (<< pipeline.parameters.in_build_account_slug >>)"
  #   post-steps:
  #     - store_artifacts:
  #         path: "language_images/ruby30/manifests"
  #   packer_working_directory: "language_images/ruby30"
  #   requires:
  #     - "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"
  ruby31-build: &ruby31-build
    <<: *packer-build
    name: "Generate Ruby 3.1 Image (<< pipeline.parameters.in_build_account_slug >>)"
    post-steps:
      - store_artifacts:
          path: "language_images/ruby31/manifests"
    packer_working_directory: "language_images/ruby31"
    requires:
      - "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"
  ruby314-build: &ruby314-build
    <<: *packer-build
    name: "Generate Ruby 3.1.4 Image (<< pipeline.parameters.in_build_account_slug >>)"
    post-steps:
      - store_artifacts:
          path: "language_images/ruby314/manifests"
    packer_working_directory: "language_images/ruby314"
    requires:
      - "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"
  ruby322-build: &ruby322-build
    <<: *packer-build
    name: "Generate Ruby 3.2.2 Image (<< pipeline.parameters.in_build_account_slug >>)"
    post-steps:
      - store_artifacts:
          path: "language_images/ruby322/manifests"
    packer_working_directory: "language_images/ruby322"
    requires:
      - "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"

workflows:
  version: 2
  build-only:
    jobs:
      - teak/packer-build:
          <<: *packer-build
      - teak/build-dependent-images:
          name: "Build base dependent images"
          region: << pipeline.parameters.region >>
          build_account_slug: << pipeline.parameters.in_build_account_slug >>
          ami_name_prefix: "base"
          requires:
            - "Generate Images (<< pipeline.parameters.in_build_account_slug >>)"
          context:
            - AWS
            - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
      # - teak/packer-build:
      #     <<: *node12-build
      # - teak/build-dependent-images:
      #     name: "Build node12 dependent images"
      #     region: << pipeline.parameters.region >>
      #     build_account_slug: << pipeline.parameters.in_build_account_slug >>
      #     ami_name_prefix: "node12"
      #     requires:
      #        - "Generate Node 12 Image (<< pipeline.parameters.in_build_account_slug >>)"
      #     context:
      #       - AWS
      #       - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
      # - teak/packer-build:
      #     <<: *ruby30-build
      # - teak/build-dependent-images:
      #     name: "Build ruby30 dependent images"
      #     region: << pipeline.parameters.region >>
      #     build_account_slug: << pipeline.parameters.in_build_account_slug >>
      #     ami_name_prefix: "ruby30"
      #     requires:
      #        - "Generate Ruby 3.0 Image (<< pipeline.parameters.in_build_account_slug >>)"
      #     context:
      #       - AWS
      #       - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
      - teak/packer-build:
          <<: *ruby31-build
      - teak/build-dependent-images:
          name: "Build ruby31 dependent images"
          region: << pipeline.parameters.region >>
          build_account_slug: << pipeline.parameters.in_build_account_slug >>
          ami_name_prefix: "ruby31"
          requires:
             - "Generate Ruby 3.1 Image (<< pipeline.parameters.in_build_account_slug >>)"
          context:
            - AWS
            - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
      - teak/packer-build:
          <<: *ruby314-build
      - teak/build-dependent-images:
          name: "Build ruby314 dependent images"
          region: << pipeline.parameters.region >>
          build_account_slug: << pipeline.parameters.in_build_account_slug >>
          ami_name_prefix: "ruby314"
          requires:
             - "Generate Ruby 3.1.4 Image (<< pipeline.parameters.in_build_account_slug >>)"
          context:
            - AWS
            - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
      - teak/packer-build:
          <<: *ruby322-build
      - teak/build-dependent-images:
          name: "Build ruby322 dependent images"
          region: << pipeline.parameters.region >>
          build_account_slug: << pipeline.parameters.in_build_account_slug >>
          ami_name_prefix: "ruby322"
          requires:
             - "Generate Ruby 3.2.2 Image (<< pipeline.parameters.in_build_account_slug >>)"
          context:
            - AWS
            - CircleCI # Needed to trigger CI pipelines.  Current token is owned by Jon Frisby, and will need to be changed if he ever leaves the org.
