---
- hosts: all
  become: yes

  tasks:
    - name: Install dogstatsd
      shell: |
        bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
      environment:
        DD_AGENT_MAJOR_VERSION: "{{ dd_agent_major_ver }}"
        DD_API_KEY: "{{ dd_api_key }}"
        DD_SITE: "datadoghq.com"
